title: Ultralytics Inference Serving API
version: 1.0.0
models:
  - name: yolov8n
    path: yolov8n.onnx # path to model file, i.e. yolov8n.pt, yolov8n.yaml
    task: detect  # inference task, i.e. detect, segment, classify
    imgsz: 640  # size of input images as integer or w,h
    conf: 0.5 # object confidence threshold for detection (default 0.25 predict, 0.001 val)
